### ISSUE TITLE
Bezüge zu Kirche ... 

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/viecpro-nuxt#103]
- sometimes labels for persons are missing
- relation types are missing
- Geburtsdatum / Sterbedatum needs to be changed to Beginn / Ende
- Nachname should be "name"

**Comment by kaggl** [comment]
Are there any examples?

**Comment by sennierer** [comment]
eg here https://viecpro-frontend.acdh-ch-dev.oeaw.ac.at/de/detail/persons/219685
or here https://viecpro-frontend.acdh-ch-dev.oeaw.ac.at/de/detail/persons/323043

**Comment by kaggl** [comment]
this is the response i get from the backend
![image](https://github.com/acdh-oeaw/viecpro-nuxt/assets/48437174/36785ac0-f14b-4b4e-b106-af8e851397a0)
this is what is shown in the frontend (with adapted translations)
![image](https://github.com/acdh-oeaw/viecpro-nuxt/assets/48437174/01f61157-dcaf-4204-85b2-9f453536c517)

Which information is missing?
