### ISSUE TITLE
sort order select popover not aligend with trigger button

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/viecpro-nuxt#121]
currently, the sort order select does not align the popover to the trigger button:

![Screenshot_20240510_140452](https://github.com/acdh-oeaw/viecpro-nuxt/assets/20753323/0498d6dc-86fa-44cb-b5e5-6c1c83114126)

also, i think it would be good to set a min-width on the popover to match the trigger button width (i.e. the popover should not be narrower than the trigger button)

**Comment by kaggl** [comment]
the min-width already matches the trigger button, the options window is just off

**Comment by stefanprobst** [comment]
this looks a bit too narrow

![Screenshot_20240513_171439](https://github.com/acdh-oeaw/viecpro-nuxt/assets/20753323/2df7c1bf-721f-4430-ab39-11faf26e421b)

**Comment by kaggl** [comment]
seems to be firefox only, I will look into it
