### ISSUE TITLE
change table "Sonstiger Bezug und Tätigkeit" to three columns

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/viecpro-nuxt#134]
3 columns:
- Art des Bezuges
- Beginn
- Ende

Remove the column "Name"

**Comment by kaggl** [comment]
we might have a bigger problem here: non court functions is an array (the only one) that has labels but also relations. is this intended?

**Comment by sennierer** [comment]
actually they changed the data, so that there are no labels included anymore. see https://github.com/acdh-oeaw/viecpro-backend-devops/issues/110 . Thats not in the type indexes yet, but it has already been changed in the data.
