### ISSUE TITLE
cant link to or refresh certain detail pages

### ISSUE THREAD

**Issue by kaggl** [acdh-oeaw/viecpro-nuxt#140]
this is a query problem with high priority

**Comment by stefanprobst** [comment]
is this about this error?

---

on the relations search page https://viecpro-frontend.acdh-ch-dev.oeaw.ac.at/en/search/relations, when clicking on a place in the "Source: Name" column, i am navigated to a place detail page, e.g. https://viecpro-frontend.acdh-ch-dev.oeaw.ac.at/en/detail/places/346389 - however, this page fails to load and instead displays "Request failed with HTTP code 404 | Server said: Could not find a document with id: Place_346389"

**Comment by kaggl** [comment]
no this seems to be a typesense issue
