### ISSUE TITLE
remove the `Relationen` menu entry from list views

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/viecpro-nuxt#153]
in the list views one of the entries is this relationen entry, this needs to be removed.

![screenshot_viecpro_relationen_2024-10-02](https://github.com/user-attachments/assets/85f2ddaf-7194-4b25-8242-2b5b637a8ecf)

**Comment by stefanprobst** [comment]
closed by https://github.com/acdh-oeaw/viecpro-nuxt/commit/3125139a3ec397bfaac9a59e13b398823dd52541
