### ISSUE TITLE
add two new items in left menu of list views

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/viecpro-nuxt#154]
"Literaturverzeichnis" and "Funktionsregister". Both should be greyed out (for the moment), beneath Orte (after "Relationen" has been removed, see #153) and maybe slightly separated from the rest (eg via a horizontal line)

**Comment by stefanprobst** [comment]
only "Funktionsregister" should be disabled (greyed out"

"Literaturverzeichnis" should display zotero group library

**Comment by stefanprobst** [comment]
closed by https://github.com/acdh-oeaw/viecpro-nuxt/commit/b3d76730c86c5b34c19f52a50d4658c7815b5eb2

zotero library feature tracked in #160
