### ISSUE TITLE
not all substrings are matched by the search

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/viecpro-nuxt#62]
eg a [search for "Nikolsburg"](https://viecpro-frontend.acdh-ch-dev.oeaw.ac.at/de/search/persons?q=Nikolsburg&page=1) should bring up "Dietrichstein-Nikolsburg" but it doesnt. If you search for Dietrichstein you'll find the hist on the [last page](https://viecpro-frontend.acdh-ch-dev.oeaw.ac.at/de/search/persons?q=Dietrichstein&page=5)

**Comment by kaggl** [comment]
Typesense is not able to search substrings of whole words. However since v0.22.2 there is an option to put the hyphen as a "token separator", this would make it possible to look up nikolsburg.
This would have to be implemented into the typesense backend.
