### ISSUE TITLE
Translation of column names should be consistently German

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/viecpro-nuxt#66]
Given that currently there is no English Data the translation of the column names should be German. 
Eg in https://viecpro-frontend.acdh-ch-dev.oeaw.ac.at/de/detail/persons/331952 in "Funktionen am Hof" it should be "Ende" instead of "End"

**Comment by kaggl** [comment]
why?

**Comment by sennierer** [comment]
The rest of the headings are German (eg "Funktionen am Hof"), so I would suggest to make all of them German.
