### ISSUE TITLE
move "Beziehung zu Orten" one level up

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/viecpro-nuxt#87]
currently "beziehungen zu Orten" is beneath "Bezüge zum Wiener Hof", but it should be on the same level as "Bezüge zum Wiener Hof"
![screenshot-viecpro-frontend acdh-ch-dev oeaw ac at-2024 03 20-14_20_05](https://github.com/acdh-oeaw/viecpro-nuxt/assets/499265/e9e392c9-6ad1-47b4-afec-e5d720dabc5f)

**Comment by kaggl** [comment]
You mean it should have its own heading with the same title as the disclosure itself? wouldnt it make more sense if i moved it down to Weitere Informationen? @sennierer

**Comment by sennierer** [comment]
yes, makes sense, move it down to Weitere Information @kaggl
